### ISSUE TITLE
Any chance at pushing a non Amazon Image to dockerhub?

### ISSUE THREAD

**Issue by Thell** [mattgodbolt/gcc-explorer-image#1]
The last few days I've been having some fun with gcc explorer and thought I'd give a go at building a local docker image when I saw this repo, but it didn't go so well because of the s3cfg stuff. Perhaps I should just build from the main repo in a dockerfile?

**Comment by mattgodbolt** [comment]
Hi there!

This is pretty much a personal project for Amazon : running GCC explorer is
something I usually do locally with 'make'.

That said it'd be a good idea to make this a bit easier to use. My main
reason for not opening up the GCC images is because I have a (very old)
licensed version of Intel's compiler that I can't distribute.

I'll have a think about this. I'm not especially happy with my current
docker setup as it is!

**Comment by Thell** [comment]
Roger on that. The main gcc-explorer repo is definitely easy enough to use so no worries there. I'll just need to read up a bit about the setup to do gcc and clang and additions to the includes. Thanks for the cool tool!
